"""Bonus mini-product UI — Lab 17 memory agent demo (STUDENT starter).

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by OpenAI grounded in the
   retrieved memory context (gpt-4.1-mini by default).

The page shell, budget metrics, and OpenAI chat are wired for you. Your job is
the ONE function marked `BONUS TODO`: `retrieve_for_case(...)`.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import generate_reply, openai_available
from src.memory_student import StudentMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, load_dataset, load_json
from src.zep_common import get_zep_client

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

CSS = """
<style>
.block-container { padding-top: 1rem; max-width: 1440px; }
.lab-badge {
    display:inline-block; padding:2px 10px; border-radius:999px;
    color:#fff; font-size:0.75rem; font-weight:600; letter-spacing:.02em;
    margin-right:6px;
}
.lab-card {
    border:1px solid rgba(128,128,128,.25); border-radius:12px;
    padding:10px 14px; margin:8px 0; background:rgba(127,127,127,.06);
}
.lab-kv { font-size:0.85rem; opacity:.85; }
.lab-kv b { opacity:1; }
.stChatMessage { border-radius:12px; padding:0.5rem 0.75rem; }
[data-testid="stMetric"] { border:1px solid rgba(128,128,128,.2); border-radius:8px; padding:6px 10px; }
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    return f"{case['id']} · {case['expected_layer']} · {case['user_id']}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    return f'<span class="lab-badge" style="background:{color}">{layer}</span>'


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """BONUS TODO: run student retrieval for the loaded case.

    Return a dict with keys:
      - "merged_context": str  (StudentMemory.assemble_context output)
      - "layers": dict[str, str]  (per-layer evidence: short_term/long_term/
                                   episodic/semantic)
      - "budget": dict  (the breakdown from assemble_context)

    Hints:
      * Build short_term from case["fixture_messages"] if present, else from
        the matching user/thread messages in data/sessions.json, plus
        extra_messages. E01 has no fixture — it uses thread minh-s1.
      * Decide which durable layers to fetch from case["expected_layer"] (or
        case["retrieve_layers"] for "mixed"), then call
        memory.retrieve_long_term / retrieve_episodic / retrieve_semantic.
      * Keep user_id and thread_id from the loaded case.
      * Finish with memory.assemble_context(layers).
    """
    messages = list(case.get("fixture_messages") or [])
    if not messages:
        for user in load_dataset().get("users") or []:
            if user.get("user_id") != case.get("user_id"):
                continue
            for session in user.get("sessions") or []:
                if session.get("thread_id") == case.get("thread_id"):
                    messages.extend(session.get("messages") or [])

    short_term = ShortTermMemory(strategy="sliding")
    for message in [*messages, *extra_messages]:
        short_term.add(message.get("role", "user"), message.get("content", ""))

    layers = {
        "short_term": short_term.render(),
        "long_term": "",
        "episodic": "",
        "semantic": "",
    }
    requested = case.get("retrieve_layers") or [case.get("expected_layer")]
    query = case.get("query", "")
    user_id = case.get("user_id", "")
    thread_id = case.get("thread_id", "")
    if "long_term" in requested:
        layers["long_term"] = memory.retrieve_long_term(user_id, thread_id, query)
    if "episodic" in requested:
        layers["episodic"] = memory.retrieve_episodic(user_id, query)
    if "semantic" in requested:
        layers["semantic"] = memory.retrieve_semantic(settings.semantic_graph_id, query)

    merged_context, budget = memory.assemble_context(layers)
    return {"merged_context": merged_context, "layers": layers, "budget": budget}


def main() -> None:
    st.set_page_config(page_title="Lab 17 Memory Demo", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)
    st.title("🧠 Lab 17 — Memory Agent Demo")
    st.caption("Load a test case, inspect layered retrieval, then keep chatting as that user.")

    with st.sidebar:
        st.header("⚙️ Setup")
        zep_ok = bool(settings.zep_api_key)
        st.markdown(("✅" if zep_ok else "⚠️") + " Zep API key "
                    + ("configured" if zep_ok else "missing"))
        st.markdown(("✅" if openai_available() else "⚠️") + " OpenAI key "
                    + ("configured" if openai_available() else "missing"))
        st.caption(f"Chat model: `{settings.openai_model}`")
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        default_case = next(
            (i for i, item in enumerate(cases) if item.get("expected_layer") == "mixed"),
            0,
        )
        chosen = st.selectbox("Test case", labels, index=default_case)
        case = cases[labels.index(chosen)]

    st.markdown(
        f'{layer_badge(case.get("expected_layer", "?"))} <b>{case["id"]}</b> '
        f'<span class="lab-kv">User: {case.get("user_id", "-")} · '
        f'Thread: {case.get("thread_id", "-")}</span>',
        unsafe_allow_html=True,
    )
    st.caption(case.get("query", ""))
    st.caption(case.get("description", ""))

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    if st.button("Run retrieval", type="primary", use_container_width=True):
        try:
            memory = StudentMemory(get_zep_client())
            st.session_state.last_result = retrieve_for_case(memory, case, st.session_state.chat)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)

    retrieval_col, chat_col = st.columns([3, 2], gap="large")
    with retrieval_col:
        st.markdown("### Retrieval evidence")
        result = st.session_state.get("last_result")
        if result:
            active = [k for k, value in result["layers"].items() if value.strip()]
            st.markdown(
                " ".join(layer_badge(layer) for layer in active) or "_(nothing retrieved)_",
                unsafe_allow_html=True,
            )
            cols = st.columns(4)
            for i, layer in enumerate(("short_term", "long_term", "episodic", "semantic")):
                budget = result.get("budget", {}).get(layer, {})
                cols[i].metric(
                    layer.replace("_", " "),
                    f"{budget.get('used_tokens', 0)} tok",
                    help=f"limit {budget.get('limit_tokens', 0)} · raw {budget.get('raw_tokens', 0)}",
                )
            for name, text in result["layers"].items():
                if text.strip():
                    preview = text.replace("\n", " ")[:360]
                    st.markdown(f"**{name.replace('_', ' ')}** · `{preview}`")
                    with st.expander(f"Full {name.replace('_', ' ')} evidence"):
                        st.code(text, language="markdown")
            context_preview = (result.get("merged_context") or "(empty)").replace("\n", " ")[:420]
            st.caption(f"Merged context: {context_preview}")
            with st.expander("Full merged context (budget-trimmed)"):
                st.code(result.get("merged_context") or "(empty)", language="markdown")
        else:
            st.info("Run retrieval to populate layer evidence and token budgets.")

    with chat_col:
        st.markdown("### Grounded OpenAI chat")
        st.caption(f"Model: `{settings.openai_model}` · Context is refreshed every turn.")
        for msg in st.session_state.get("chat", []):
            with st.chat_message(msg["role"]):
                st.write(msg["content"])
        prompt = st.chat_input("Ask a follow-up as this user…")
        if prompt:
            st.session_state.chat.append({"role": "user", "content": prompt})
            try:
                memory = StudentMemory(get_zep_client())
                follow = retrieve_for_case(memory, {**case, "query": prompt}, st.session_state.chat)
                st.session_state.last_result = follow
                context = follow.get("merged_context", "")
                if openai_available():
                    reply = generate_reply(context, st.session_state.chat[:-1], prompt)
                else:
                    reply = ("_(OpenAI key missing — showing retrieved context instead)_\n\n"
                             + (context[:1500] or "(no memory retrieved)"))
                st.session_state.chat.append({"role": "assistant", "content": reply})
                st.rerun()
            except Exception as exc:  # noqa: BLE001
                st.exception(exc)


if __name__ == "__main__":
    main()
